

env = Environment()
#env.Replace(CXX = 'clang++')
env.Append(CCFLAGS = ['-std=c++11', '-stdlib=libc++'])
env.Append(LINKFLAGS = ['-stdlib=libc++'])
env.Append(CPPPATH = ['../../../'])
program = env.Program( 'test', ['src/main.cpp'])

testAlias = Alias( 'test', [program], program[0].path )

AlwaysBuild(testAlias)
