env = Environment()
env.Append(CCFLAGS = ['-std=c++11', '-stdlib=libc++'])
env.Append(CPPPATH = ['../../../../../'])
env.Append(LINKFLAGS = ['-stdlib=libc++'])

env.Program( 'crutch', ['main.cpp', '../../../../lib/core/assert.cpp'] )